### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by chiefnoah** [xorvoid/forsp#5]
Please, I'd like to poke around this :)

**Comment by pbrochard** [comment]
Same here. Thanks.

**Comment by xorvoid** [comment]
Will add a CC0 or similar when I get a chance. Feel free to play. I have no commercial interests. If you find value (even commercial), I'd only ask that you cite me.

**Comment by xorvoid** [comment]
Added MIT License: Enjoy!
