### ISSUE TITLE
`build.sh` says C99, but `struct obj` uses anonymous union

### ISSUE THREAD

**Issue by AlexBlandin** [xorvoid/forsp#9]
Switching to `-std=c11` (assuming DR 499, else `c17`) works; otherwise, the tagged union needs to be a little more old-school (just giving the union a name (`} data;`) and dealing with the indirection (`->data.num`, etc)). See PR #10 for an illustrative diff. (Not that I recommend going this route, personally the anonymous union is significantly nicer, but if proper C99 compliance is desired...)

```
forsp.c:65:3: error: anonymous unions are a C11 extension [-Werror,-Wc11-extensions]
   65 |   union {
      |   ^
```

**Comment by xorvoid** [comment]
I'm okay switching to C11. It would be pretty easy to backport to even C89 if someone cared.

**Comment by AlexBlandin** [comment]
Feels like the best approach. I don't see anywhere else specify it, so the PR #12 only touches `build.sh` for now.
